module.exports = {
  products: [
    {
      id: '1',
      Name: 'Cheeba Chews | Sativa Chocolate Taffy',
      integrationKey: 'Cheeba Chew SATIVA 100mg',
      Options: ['0.1g'],
      type: 'Edible',
      medicalOnly: false,
      recOnly: true,
      strainType: 'Sativa',
      Image: 'https://s3-us-west-2.amazonaws.com/dutchie-images/3a12519ed29b7b7bc58090c1ed73d16f',
      Prices: ['20.0000'],
      medicalPrices: ['20.0000'],
      recPrices: ['20.0000'],
      Status: 'Active',
      flavors: ['chocolate'],
      effects: { Creative: 8, Energetic: 9, Focused: 8, Happy: 9, Inspired: 8 },
      weight: 1050,
      integration: true,
      Description:
        'Sativa infused Cheeba Chews™ are known for their consistency in producing an uplifting “head high”. Perfect for creative inspiration or a little added motivation when you’re on the go, these individually dosed 3 gram chocolate taffy chews are a perfect compliment to an active lifestyle.\n\nEach batch of high grade cannabis oil used to make Cheeba Chews™ is tested at three critical stages…The Flower, The Oil, The Edible…to ensure each individual chew is consistently infused.\n\nINGREDIENTS: Sugar, Glucose Syrup, Vegetable Oil, Skim Milk, Cocoa, Whey, Butter, Soy Lecithin, Flavorings | Calories: 80\n',
      THCContent: '100',
      CBDContent: '0',
      DispensaryID: '54321',
      updatedAt: '2019-05-31T19:00:19.121Z',
      createdAt: '2019-02-05T00:13:39.014Z',
      syncedAt: '2019-05-31T19:00:19.121Z',
      score: 5,
      brandName: 'Cheeba',
      descriptionHtml:
        '<p>Sativa infused Cheeba Chews™ are known for their consistency in producing an uplifting “head high”. Perfect for creative inspiration or a little added motivation when you’re on the go, these individually dosed 3 gram chocolate taffy chews are a perfect compliment to an active lifestyle.</p><p><br></p><p>Each batch of high grade cannabis oil used to make Cheeba Chews™ is tested at three critical stages…The Flower, The Oil, The Edible…to ensure each individual chew is consistently infused.</p><p><br></p><p>INGREDIENTS: Sugar, Glucose Syrup, Vegetable Oil, Skim Milk, Cocoa, Whey, Butter, Soy Lecithin, Flavorings | Calories: 80</p>',
      duplicatedProductId: '98765',
      quantities: [{ option: '0.1g', productID: 9970, quantity: 28 }],
    },
    {
      id: '2',
      CBDContent: 15,
      Description:
        'Eclipse is a Caribbean Splash fruit purée gummy with a hybrid THC distillate/RSO blend. Purefectionery blends their fruit purée using only the finest Blood Orange, Guava, and Tamarind. When you need the feeling of a tropical breeze across your face and in your mouth, these Hybrid Soft Chews will enhance your day or night.\n',
      descriptionHtml:
        '<p>Eclipse is a Caribbean Splash fruit purée gummy with a hybrid THC distillate/RSO blend. Purefectionery blends their fruit purée using only the finest Blood Orange, Guava, and Tamarind. When you need the feeling of a tropical breeze across your face and in your mouth, these Hybrid Soft Chews will enhance your day or night.</p>',
      DispensaryID: 'Mg9zee236E9j3EE7J',
      duplicatedProductId: 'dzLavFcq8esNXdpZ2',
      effects: {
        Calm: 9,
        Energetic: 5,
        Happy: 8,
        Relaxed: 6,
        'Pain-Relief': 5,
      },
      Image: 'https://s3-us-west-2.amazonaws.com/dutchie-images/e9da65afc7bcf48c3f9c6bcdd69d024d',
      medicalOnly: false,
      medicalPrices: [15],
      Name: 'Purefectionery | Eclipse Gummies',
      Options: ['Purefectionery | Eclipse Gummies'],
      Prices: [18],
      recPrices: [18],
      Status: 'Active',
      strainType: 'Hybrid',
      THCContent: 20,
      type: 'Edible',
      weight: 2361,
      score: 5,
      createdAt: new Date('2019-05-13T18:06:05.414Z'),
      updatedAt: new Date('2019-06-13T23:16:19.283Z'),
      integration: false,
      cName: 'purefectionery-eclipse-gummies',
    },
    {
      id: '3',
      CBDContent: 30,
      Description: 'Hybrid by Pintail Gardens \n',
      descriptionHtml: '<p>Hybrid by Pintail Gardens</p>',
      DispensaryID: 'wbf5NjWG8akWvwL3M',
      effects: {
        Calm: 9,
        Energetic: 5,
        Happy: 8,
        Relaxed: 6,
        'Pain-Relief': 5,
      },
      Image:
        'https://images.dutchie.com/96fc1f04dc41226a87cb4cf68cf57ff4?auto=format&dpr=1&bg=FFFFFF&max-h=291&max-w=409&min-h=291&min-w=409&crop=faces&fit=crop&w=409&h=auto&ixlib=react-7.2.0',
      medicalOnly: false,
      medicalPrices: [9, 27, 54, 108, 206],
      Name: 'Cookie Dawg',
      Options: ['1g', '1/8oz', '1/4oz', '1/2oz', '1oz'],
      Prices: [10.8, 32.4, 64.8, 129.6, 247.2],
      recPrices: [10.8, 32.4, 64.8, 129.6, 247.2],
      Status: 'Active',
      strainType: 'Hybrid',
      THCContent: 29,
      type: 'Flower',
      weight: 1209,
      score: 5,
      createdAt: new Date('2019-06-28T21:59:23.576Z'),
      connectedAt: new Date('2019-07-14T23:23:50.642Z'),
      updatedAt: new Date('2019-07-21T19:02:57.772Z'),
      integration: false,
      cName: 'cookie-dawg',
    },
  ],
};
